export class OfficerLookup {
	static abilities: Map<string, string|string[]> = new Map<string, string|string[]>([
		["Computer Precision", "0718"],
		["Shield Remodulation", "Ahvix"],
		["Cybernetic Tactician", "Airiam"],
		["Powered Armor", "Arix"],
		["Shields Refactor", "Arkady"],
		["Diversify", "Arrock"],
		["Weapon Contribution", "Azetbur"],
		["Whee! Murder!", "Badgey"],
		["Romulan Tact", "Ba'el"],
		["Deceptive Weakness", "Barot"],
		["Get It Together!", "Beckett Mariner"],
		["Persistence Is Key", "Benjamin Sisko"],
		["Varied Income Streams", "B'Etor"],
		["Unshakeable Moral Code", "Beverly Crusher"],
		["Excellent Medicine", "Bones"],
		["The Real Action", "Brad Boimler"],
		["Tactician", "Cadet Kirk"],
		["Psychologist", "Cadet McCoy"],
		["Warp Theory", "Cadet Scotty"],
		["Fighting Spirit", "Cadet Sulu"],
		["Negotiations", "Cadet Uhura"],
		["Sadistic", "Captain Tilly"],
		["Weapons Expert", "Carol"],
		["Show Them What You Can Do", "Cath"],
		["Dogs of War", "Chang"],
		["Know Your Enemy", "Changeling Kira"],
		["Mind Games", "Charvanek"],
		["Energy Absorber", "Chen"],
		["Learned from the Best", "Culber"],
		["Liquid Courage", "Damar"],
		["Interceptor Trainer", "Darwin"],
		["Effort Yields Its Own Rewards", "Data"],
		["Nemesis", "Deanna Troi"],
		["Honor Guard", "Decius"],
		["Sharpen Defenses", "D'Jaoki"],
		["Hurry Home", "Domitia"],
		["Hidden Stash", "Dupont"],
		["Yay, Friends!", "D'Vana Tendi"],
		["Cybernetics Enhancements", "Eight Of Eleven"],
		["Advanced Warp Theory", "Eleven Of Eleven"],
		["Bombardment", "Emperor Georgiou"],
		["Delta Quadrant Technology", "Eurydice"],
		["Cut Corners If You Need To", "Fess"],
		["You will be assimilated", "Five Of Eleven"],
		["Cargo Optimization Algorithms", "Four Of Eleven"],
		["Critical Avoidance", "Gaila"],
		["Outcast Spy", "Garak"],
		["The Mind's Eye", "Geordi La Forge"],
		["Deceptive Warfare", "Georgiou"],
		["Fight or Flight", "Ghrush"],
		["Problem Solver", "Gonzales"],
		["Military Training", "Goon"],
		["Creating Opportunities", "Gorkon"],
		["Wartime Chancellor", "Gowron"],
		["Manic Ambition", "Gul Dukat"],
		["Survey Trainer", "Hadley"],
		["Sabotage", "Harrison"],
		["823 ways to die", "Harry Mudd"],
		["Gold Rush", "Helvia"],
		["Explorer Trainer", "Hendorff"],
		["Rage of Khitomer", "Honorguard Worf"],
		["Created To Win", "Ikat'ika"],
		["Kobayashi Maru", "Instructor Spock"],
		["Warrior Spirit", "Jadzia Dax"],
		["Reinforcements", "Javaid"],
		["The Beats and Shouting!", "Jaylah"],
		["Engage", "Jean-Luc Picard"],
		["Unflinching Resolve", "Joachim"],
		["Data Miner", "Joaquin"],
		["Steady Hand", "Julian Bashir"],
		["Blood Oath", "Kang"],
		["Enhanced Weaponry", "Kati"],
		["Defensive Mining", "K'Bisch"],
		["Fine Tuning", "Keenser"],
		["Attack Maneuvers", "Kerla"],
		["Savage Tenacity", "Khan"],
		["Steel Determination", "Kira Nerys"],
		["Inspirational", "Kirk"],
		["Critical Strike", "Klaa"],
		["Resist Kinetic", "Komal"],
		["Open Them Up", "Koth"],
		["Know your Enemy", "Kras"],
		["Federation Contacts", "Krell"],
		["Watch the World burn", "Kumak"],
		["Merciless Pursue", "Kuron"],
		["Battleship Trainer", "Leslie"],
		["Defensive Tactics", "Linkasa"],
		["Bolstered", "Livis"],
		["Klingon Pursue", "L'Nar"],
		["Quick Thinking", ["Lorca", "SNW Christopher Pike"]],
		["Fear is Power", "Lursa"],
		["Isogen Mining", "Mäkinen"],
		["Wife of a Dahar", "Mara"],
		["Shady Methods", "Marcus"],
		["Let Me Help You", "Marla"],
		["Unwavering Loyalty", "Martok"],
		["Hasty Extraction", "Mavery"],
		["Slip Through", "M'Benga"],
		["Intuitive", "Michael Burnham"],
		["Luck Of The Irish", "Miles O'Brien"],
		["Acid bitterness", "Mirek"],
		["Think or Sink", "Mitchell"],
		["No Fear", "Moreau"],
		["Strengthener", "M'Ral"],
		["Down but Never Out", "Mudd"],
		["Guardian Angel", "Navi"],
		["See the Flaws", "Nero"],
		["The Dancing Doctor", "Next Gen Crusher"],
		["Power Play", "Next Gen Data"],
		["Rerouting Power", "Next Gen La Forge"],
		["The Riker Lean", "Next Gen Riker"],
		["Empathic", "Next Gen Troi"],
		["Adapt & Overcome", "Nine Of Eleven"],
		["Fluidic Strength", "Odo"],
		["Bodyguard", "One Of Eleven"],
		["Risk-Taker", "Origins Burnham"],
		["Prey Instinct", "Origins Saru"],
		["No Time To Waste", "Origins Stamets"],
		["Brute Force", "Otto"],
		["Mistakes Were Made", "Pan"],
		["Snarky Genius", "Paul Stamets"],
		["Advanced Training", "Pike"],
		["Breen Served Cold", "Pon"],
		["Blood and Honor", "Qa'Ug"],
		["Take Everything They Have", "Quark"],
		["Win Them Over", "Reginald Barclay"],
		["Systems Critical", "Rima"],
		["Fatal Charm", "Ro Mudd"],
		["Impress With Your Opulence", "Rom"],
		["Energy Boost", "Rukor"],
		["I Hope This Works...", "Sam Rutherford"],
		["Avoid Danger", "Saru"],
		["Born Engineer", "Scotty"],
		["Civilized Persistence", "Sela"],
		["Intimidation", "Sesha"],
		["Strengthen the Unimatrix", "Seven Of Eleven"],
		["Exploit Overheat", "Severus"],
		["Justice Dealer", "Shev"],
		["Defenses are irrelevant", "Six Of Eleven"],
		["Fix What Is Broken", "SNW Hemmer"],
		["Warp Overdrive", "SNW La'an"],
		["Frequency Plating", "SNW Ortegas"],
		["Heavy Shields", "SNW Spock"],
		["Pre-emptive Maneuvers", "SNW Uhura"],
		["Engine Redlining", "SNW Una"],
		["Illogical", "Spock"],
		["Pack Rat", "Stonn"],
		["Shield Backdoor", "Strike Team La'an"],
		["Thermal Modulation", "Strike Team Ortegas"],
		["Crush Their Hopes", "Strike Team Una"],
		["Ranking Fire", "Sulu"],
		["Resistance", "Tal"],
		["Code of Honor", "Tasha Yar"],
		["Tribble Mining Collective", "Ten Of Eleven"],
		["Resource Protection Protocols", "Three Of Eleven"],
		["Hold Your Horses!", "Tilly"],
		["Mirani Technology", "Tiza"],
		["Objective Defense", "T'Laan"],
		["Death Over Disgrace", "Tomalak"],
		["Security Plans", "TOS Chekov"],
		["It's all we have to go on", "TOS Kirk"],
		["Just An Old Country Doctor", "TOS McCoy"],
		["She'll launch on time", "TOS Scotty"],
		["Prosper", "TOS Spock"],
		["I'll Protect You!", "TOS Sulu"],
		["Modulation Frequency Found", "TOS Uhura"],
		["Hidden Stash", "T'Pring"],
		["Extraction Protocol", "Two Of Eleven"],
		["The Beast Inside", "Tyler"],
		["Target That Signal", "Uhura"],
		["Kinetic Boost", "Vartoq"],
		["Chirurgical Precision", "Vel"],
		["Sturdy Companion", "Vella"],
		["Feel the Heat", "Vemet"],
		["Energy Absorption", "Vixis"],
		["Traveler's Scion", "Wesley Crusher"],
		["Manipulate, Cajole, Deceive", "Weyoun"],
		["The Icarus Factor", "William T. Riker"],
		["Only Fools Have No Fear", "Worf"],
		["Interceptor Affinity", "Woteln"],
		["Wolf among the ships", "Yan'Agh"],
		["Romulan Grudge", "Yuki"],
		["Home Engineer", "Zahra"],
		["Upper hand", "Zhou"]
	]);
}